---
- name: preparing database installation template
  template: src=db-install-11g.rsp.j2 dest=/tmp/db-install.rsp

#- name: update required pre-requisites
#  shell: "sed -i -e 's/<RUNLEVEL>/<RUNLEVEL SEVERITY=\"IGNORABLE\">/g' {{ oracle_database_installer_directory }}/stage/cvu/cvu_prereq.xml"

- name: run installer
  shell: "{{ oracle_database_installer_directory }}/runInstaller -silent -waitforcompletion -ignoreSysPrereqs -responseFile /tmp/db-install.rsp"
  args:
    creates: "{{ oracle_database_oracle_home }}/bin/sqlplus"
  become: yes
  become_user: oracle
  register: command_result
  failed_when: "'Successfully Setup Software.' not in command_result.stdout_lines"

- name: installation results
  debug:
    var: command_result

- name: run post-installation scripts as root
  shell: "{{item}}"
  with_items:
    - "{{ oracle_database_inventory_location }}/orainstRoot.sh"
    - "{{ oracle_database_oracle_home }}/root.sh"

- name: set oracle home
  lineinfile:
   dest: "/home/oracle/.bash_profile"
   regexp: "^{{ item.start }}"
   line: "{{ item.start }}{{ item.end }}"
   insertbefore: "export PATH"
  become: yes
  become_user: oracle
  with_items:
    -
      start: "ORACLE_HOME="
      end: "{{ oracle_database_oracle_home }}"
    -
      start: "PATH=$ORACLE_HOME/bin:"
      end: "$PATH"
    -
      start: "export ORACLE_HOME"
      end: ""
