---
# tasks file for oracle-database
- name: install oracle database
  include: install-db.yml
  become: yes
  become_user: root
  tags:
    - installdatabase

- name: create listener oracle database
  include: create-listener.yml
  become: yes
  become_user: oracle
  tags:
    - createlistener

- name: configure instance oracle database
  include: create-instance.yml
  become: yes
  become_user: oracle
  tags:
    - createinstance

- name: configure instance service
  include: configure-instances-service.yml
  become: yes
  become_user: root
  tags:
    - configureservice
