---
# tasks file for oracle-database
- name: install oracle database
  include: install-db.yml
  become: yes
  become_user: root
  tags:
    - install_database

- name: create listener oracle database
  include: create-listener.yml
  become: yes
  become_user: oracle
  tags:
    - create_listener

- name: configure instance oracle database
  include: create-instance.yml
  become: yes
  become_user: oracle
  tags:
    - create_instance

- name: configure instance service
  include: configure-instances-service.yml
  become: yes
  become_user: root
  tags:
    - configure_service
