---
# tasks file for oracle-database
- include: validate.yml

- include: prepare-OracleLinux.yml
  when: ansible_distribution == 'OracleLinux'

- include: prepare.yml
  when: ansible_distribution != 'OracleLinux'

#- name: install oracle database
#  include: install-{{ oracle_database_version }}.yml
#  become: yes
#  tags:
#    - install

#- name: create listener oracle database
#  include: configure-listener.yml
#  become: yes
#  become_user: "{{ oracle_database_user }}"
#  tags:
#    - listener

#- name: configure instance oracle database
#  include: configure-instance.yml
#  become: yes
#  become_user: "{{ oracle_database_user }}"
#  tags:
#    - instance

#- name: configure instance service
#  include: configure-instance-service.yml
#  become: yes
#  tags:
#    - configureservice
